/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Interface;

import Windows.Window1;

public class App {
  
    public static void main(String[] args) {

        Window1 Interface1 = new Window1();
        
        Interface1.setVisible(true);
    }
}
