/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InterfaceVr2;

import Windows.Login;

public class App {

    public static void main(String[] args) {
        Login Interface1 = new Login();
        Interface1.setVisible(true);
    }
}
